#!/usr/bin/env node
/**
 * Build-time inject for Vercel (and local CI).
 * Plain static JS cannot read Vercel env at runtime — this writes config.js
 * from SUPABASE_URL / SUPABASE_ANON_KEY before the deploy ships.
 *
 * Env (any of):
 *   SUPABASE_URL | NEXT_PUBLIC_SUPABASE_URL | VITE_SUPABASE_URL
 *   SUPABASE_ANON_KEY | NEXT_PUBLIC_SUPABASE_ANON_KEY | VITE_SUPABASE_ANON_KEY
 * Optional:
 *   LEAGUE_SYNC=true|false
 *   LEAGUE_BASE_URL
 *
 * Never put service_role or the DB password in env for this PWA.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const configPath = path.join(root, 'config.js');
const DEFAULT_URL = 'https://dtctorijynmcdjtzmgnk.supabase.co';

function firstEnv(...names) {
  for (const n of names) {
    const v = process.env[n];
    if (v != null && String(v).trim()) return String(v).trim();
  }
  return '';
}

function esc(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

const url = (firstEnv('SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_URL', 'VITE_SUPABASE_URL') || DEFAULT_URL).replace(/\/+$/, '');
const anon = firstEnv('SUPABASE_ANON_KEY', 'NEXT_PUBLIC_SUPABASE_ANON_KEY', 'VITE_SUPABASE_ANON_KEY');
const leagueSync = ['1', 'true', 'yes', 'on'].includes(String(process.env.LEAGUE_SYNC || '').toLowerCase());
const leagueBase = (firstEnv('LEAGUE_BASE_URL') || 'http://127.0.0.1:47331').replace(/\/+$/, '');

if (!anon) {
  console.log('[inject-config] No SUPABASE_ANON_KEY in env — leaving config.js unchanged');
  console.log('[inject-config] Set SUPABASE_ANON_KEY (and optional SUPABASE_URL) in Vercel → Settings → Environment Variables, then redeploy.');
  process.exit(0);
}

if (anon.includes('service_role') || anon.length < 20) {
  console.error('[inject-config] Refusing to write a suspicious anon key. Use the anon public JWT only.');
  process.exit(1);
}

const body = `/* Generated by scripts/inject-config.js at build — admin/deploy only.
 * Scorers never edit this. Source: Vercel env SUPABASE_URL / SUPABASE_ANON_KEY.
 */
window.SKITTLES_CONFIG = {
  supabaseUrl: '${esc(url)}',
  supabaseAnonKey: '${esc(anon)}',
  leagueSync: ${leagueSync},
  leagueBaseUrl: '${esc(leagueBase)}',
  rubs: 2,
  fines: false
};
`;

fs.writeFileSync(configPath, body, 'utf8');
console.log('[inject-config] Wrote config.js', { supabaseUrl: url, anonKeyChars: anon.length, leagueSync });
